app/Http/Controllers/PagesController.php
resources/views/index.blade.php
routes/web.php

ルーティングの設定をしました。
追加ファイル
・App/Http/Controllers/PagesController.php
・resource/views/index.blabe.php

routingsetting

---

app/Providers/AppServiceProvider.php

app/Providers/AppSeviceProvider.phpで認証エラーが出ていたので
use Illuminate\Support\Facades\Schemaを追加しました。

RoutingAuthentication

---

app/Http/Controllers/HomeController.php
resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/register.blade.php
resources/views/home.blade.php
resources/views/layouts/app.blade.php
routes/web.php

ログイン、ログアウト、新規登録、を作成しました。
それに伴い、viewも追加されています。
動きは今後調べていきます。
https://qiita.com/zaburo/items/9fcf0f4c771e011a4d35
実行のやり方は
http://localhost/YurucharaGO/public/home
でログイン画面に行きます。

Function addition auth

---

_ide_helper.php
composer.json
composer.lock
config/app.php
database/migrations/2018_06_06_020641_create_regions_table.php
database/migrations/2018_06_06_021123_create_trophys_table.php
database/migrations/2018_06_06_021313_create_prefectures_table.php
database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_06_021445_create_events_table.php
database/migrations/2018_06_06_021525_create_obtaincards_table.php
database/migrations/2018_06_06_021605_create_obitaintrophys_table.php
resources/views/index.blade.php

マイグレーションを追加しました。
修正は加えると思いますが、ひとまずこれで
.envの
12.DB_DATABASE=yurucharago(DB名)
13.DB_USERNAME=root
14.DB_PASSWORD=null
マイグレーション実行
php artisan migrate
DBが出来ていればOK

[add]migration

---

database/seeds/DatabaseSeeder.php
database/seeds/RegionsTableSeeder.php

地方テーブル(regions)のseedを追加しました。
問題なくDBにデータは入りますが、文字コードでエラーを起こしたりする場合があります。その場合はMysqlの文字コードを変えるなどで解消することが出来ます。

[add]regions_table seeder

---

database/migrations/2014_10_12_000000_create_users_table.php

usersテーブル言われた変更どおり書き換えました。
新規登録を試した結果も動きました。
変更の確認よろしくお願いします
※余裕あるならWriteのテンプレートの作成よろしくお願いします

Fix users table maigration

---

database/seeds/DatabaseSeeder.php
database/seeds/UsersTableSeeder.php

'[add]testuserseeder'

---

database/migrations/2018_06_11_025302_update_obitaintrophys_table.php

細かいブランチ多すぎぃ！
もう少しまとめて修正依頼ください
obitaintrophys ->  obtaintrophys

[fix]table_rename

---

app/Http/Controllers/GetDataController.php
app/Models/Card.php
app/Models/Obitaintrophy.php
app/Models/Obtaincard.php
database/seeds/ObtainTrophysTableSeeder.php
resources/views/cardlist.blade.php
routes/web.php

作業中です。
Topページの都道府県Mapから指定した都道府県のカード一覧を取得する機能を実装中
Obitaintrophy(入手トロフィーのmodel)
Obtaincard(入手カードのmodel)
Card(カード一覧のmodel)
この3つのmodelを追加しました。
GetDataController(データ取得の為のコントローラー)
cardlist.blade.php(都道府県カード一覧ページ)
web.phpのルーティング
カード一覧から都道府県ごとのカードの一覧表示

[Working][add]cardlist

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_11_025302_update_obitaintrophys_table.php

マイグレーションの変更したよー！
【変更点】
reset時のエラー解決
cardsテーブルの座標カラムをジオメトリーに変更

Fix migration

---

resources/views/carddetail.blade.php
resources/views/cardlist.blade.php.1.back
resources/views/configuration.blade.php
resources/views/obtaincardlist.blade.php
resources/views/trophydetail.blade.php
resources/views/trophylist.blade.php
routes/web.php

・仮ルートの作成
・画面数に応じたViewの作成
※堂前さんの作成したカードリストのブレイドファイルはバックアップファイルとして退避しました

Add routes

---

database/seeds/CardsTableSeeder.php

[fix]cardseed_lat_log

---

app/Console/Commands/models.php
app/Console/Kernel.php

php artisan コマンドの作成
cardのモデルの動作確認
コマンドの使用例
php artisan models:card 引数(県名)

Console comand add

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/seeds/CardsTableSeeder.php

データベースを変更しました。
geometryからlatitude(緯度)longitude(経度)に変更しました。
PRPhotoを5つから3つに変更しました。

[fix]DBlatlng

---

app/Http/Controllers/GetDataController.php
app/Models/Card.php
resources/views/cardDetail.blade.php
routes/web.php

ナビゲーション用の緯度経度をナビゲーション画面に渡す機能を追加しました。

[fix]latlngdata

---

public/js/navigate.js
resources/views/characterNavigation.blade.php
resources/views/searchCard.blade.php

ルート探索機能と、周辺1kmのゆるキャラ表示機能を分離しました。

[fix]navigation

---

app/Models/Card.php

[add]rengeSearch

---

resources/views/auth/login.blade.php
resources/views/auth/register.blade.php

[UPDATE]register style applied

---

app/Http/Controllers/GetDataController.php
app/Http/Controllers/ObtainDataController.php
app/Models/Obtaincard.php
public/js/mapview.js
resources/views/searchCard.blade.php
routes/web.php

[add]cardget

---

app/Http/Controllers/CollectionController.php
app/Http/Controllers/ObtainDataController.php
app/Models/Obtaincard.php
public/js/mapview.js
public/js/navigate.js
resources/views/characterNavigation.blade.php
resources/views/index.blade.php
resources/views/layouts/app.blade.php
resources/views/obtaincardlist.blade.php
routes/web.php

[add]mycardlist

---

routes/web.php

login_check

---

public/js/mapview.js

[add]circle

---

public/css/style.css
resources/views/layouts/app.blade.php

app.blead.phpの共通部分にブラウザバック機能追加
ブラウザバックボタンの画像が完成し次第、画像も追加予定

[UPDATE]app.blead.php browserback_button

---

resources/views/characterNavigation.blade.php
resources/views/searchCard.blade.php

[fix]Maplang-english

---

public/css/style.css

ログインと新規登録ページのボタンの色、シャドウを変更
いじったのはstyle.cssのみ

[UPDATE]button_color

---

public/js/navigate.js
resources/views/characterNavigation.blade.php

ナビゲーション(ルート検索)での所要時間・距離の表示処理を作成しました。

[add]showTime

---

public/js/navigate.js
resources/views/characterNavigation.blade.php

英語に対応しました。
ナビゲーションで、選ばれたカードに対応するゆるキャラアイコン表示機能を追加しました。

[add]enAndNaviNewIcon

---

app/Models/Card.php
config/database.php
database/migrations/2018_06_28_061109_create_prs_table.php
database/seeds/EventsTableSeeder.php
public/js/mapview.js
resources/views/cardDetail.blade.php
resources/views/cardList.blade.php
resources/views/characterNavigation.blade.php
resources/views/index.blade.php

DBの更新に伴い、全ページのmodel、bladeを変更しました。

[fix]allpage

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_28_054738_create_attributes_table.php
database/seeds/CardsTableSeeder.php

Color delete

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_28_054738_create_attributes_table.php

migrationのcreate_card_tableからCardColorカラム削除
create_attributes_tableにCardDesignPathカラム追加

AttributeTable_Update

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_28_054738_create_attributes_table.php

Attribute table update2

---

app/Console/Commands/Obtaintrophyslist.php
app/Http/Controllers/ObtainDataController.php
app/Models/Obitaintrophy.php
app/Models/Obtaincard.php
resources/views/layouts/app.blade.php
resources/views/trophylist.blade.php
routes/web.php

トロフィー用のカードデータ集計モデルを作成しました。
追加に伴いルーティングも変更しました。

[add]trophy

---

database/seeds/CardsTableSeeder.php
database/seeds/PRsTableSeeder.php

[fix]cardseed

---

public/js/mapview.js

半径100mの円の描画機能を追加しました。
マップの色を変更可能です。

[add]search100m

---

database/migrations/2018_06_06_021400_create_cards_table.php
database/migrations/2018_06_28_061109_create_prs_table.php

E-R図通りにデータベースを変更
都道府県IDをPRテーブルから削除
都道府県IDをカードテーブルに追加

[fix]maigrate

---

app/Models/Obitaintrophy.php

[fix]trophy

---

public/css/style.css

[FIX]login

---

app/Models/Card.php

カード一覧を取得するモデルの作成
ユーザIDは固定値のままなので後に変更が必要

[fix]card.php

---

app/Models/Card.php

[fix]Card.php rangeData

---

app/Http/Controllers/GetDataController.php
app/Models/Card.php
app/Models/Obtaincard.php
public/css/style.css
resources/views/cardDetail.blade.php
resources/views/cardList.blade.php
resources/views/obtaincardlist.blade.php
routes/web.php

現状完成しているページには全てアクセスできます。
- 未入手カードのイラストシルエット化

[fix]backandfront

---

app/Http/Controllers/GetDataController.php
public/js/topmap.js
resources/views/cardDetail.blade.php
resources/views/cardList.blade.php
resources/views/characterNavigation.blade.php

カードのPR画像、PR文をデータべーすから取得したデータに変更しました。
その他細かい修正を加えました。

[fix]cardDitail

---

public/css/style.css
public/js/topmap.js
resources/views/index.blade.php

[UPDATE]japanmap

---

public/js/mapview.js
resources/views/searchCard.blade.php

[add]clickOnly100m

---

app/Http/Kernel.php
app/Http/Middleware/DataFillter.php
app/Http/Middleware/GetDataFillter.php
app/Http/Middleware/ObtainCardFillter.php
app/Http/Middleware/RangeFillter.php
routes/web.php

各リンク先にフィルターを作成しリクエストデータを取得できなかった場合にtopページに繊維するようにしました

[add]fillter

---

public/css/style.css
resources/views/cardDetail.blade.php

[UPDATE]slider

---

routes/web.php

[fix]route

---

public/js/mapview.js
resources/views/searchCard.blade.php

新しいはてなアイコンをマップ上に表示する機能を追加しました。

[add]showNewHatena

---

public/js/trophy.js
resources/views/trophylist.blade.php

[fix]trophyview

---

app/Http/Middleware/TrustProxies.php

[fix]proxice

---

resources/views/layouts/app.blade.php

[fix]jquery

---

public/css/style.css
resources/views/cardDetail.blade.php

cardDetailのスライダーとマップレイアウト変更
PR文の枠を吹き出しに変更

[UPDATE]Card detail slider

---

app/Http/Middleware/GetDataFillter.php
database/seeds/DatabaseSeeder.php

[fix]ditail

---

public/css/style.css
resources/views/cardDetail.blade.php

[FIX]card_detail

---

public/js/mapview.js

[fix]mapajax

---

public/css/style.css
resources/views/cardList.blade.php

cardlistのシルエット化されているカードのデザイン修正

[FIX]cardlist

---

public/css/style.css

[FIX]card_list margin

---

database/seeds/DatabaseSeeder.php
public/js/navigate.js
resources/views/auth/login.blade.php

●ナビゲーション画面での吹き出しを英語表記にしました。
●ログイン画面の入力フォームを英語表記にしました。

[add]navigateEnglish

---

public/css/style.css

[FIX]accodion color

---

public/css/map.css

[FIX]update btn

---

public/js/mapview.js

[fix]mapjs

---

public/css/style.css

[fix]cahra_none

---

public/js/navigate.js

[add]navigateReload

---

resources/views/trophylist.blade.php

[fix]トロフィーの計算

---

resources/views/auth/register.blade.php

[fix]表記を英語に変更

---

public/css/style.css

カードリストの名前が2行になってはみ出している部分の修正
カード詳細の吹き出しとスライダーのボタン位置修正

[FIX]minor fix

---

database/seeds/ObtaincardTableSeeder.php
database/seeds/UsersTableSeeder.php

[add]testdata

---

app/Models/Obitaintrophy.php
database/seeds/ObtaincardTableSeeder.php

[afix]trophymodel
